### ISSUE TITLE
pm2 or forever not working

### ISSUE THREAD

**Issue by garywu520** [huggingface/Mongoku#71]
Platform: Mac
shell: zsh
```
$ mongoku --forever start 
  __  __                         _          
 |  \/  | ___  _ __   __ _  ___ | | ___   _ 
 | |\/| |/ _ \| '_ \ / _` |/ _ \| |/ / | | |
 | |  | | (_) | | | | (_| | (_) |   <| |_| |
 |_|  |_|\___/|_| |_|\__, |\___/|_|\_\\__,_|    
Error while launching with forever:  Error: Command failed: forever --uid mongoku start -a /usr/local/lib/node_modules/mongoku/dist/server.js
/bin/sh: forever: command not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'forever --uid mongoku start -a /usr/local/lib/node_modules/mongoku/dist/server.js'
}
```

**Comment by garywu520** [comment]
This is no longer my confusion, I solved it through supervisor. 
```
[program:mongoku]
command=/usr/local/bin/node /usr/local/bin/mongoku --uid mongoku start -a /usr/local/lib/node_modules/mongoku/dist/server.js
stdout_logfile=~/mongoku.log
stderr_logfile=~/mongoku.log
autostart=true
autorestart=true
startsecs=5
priority=1
stopasgroup=true
killasgroup=true
```
