### ISSUE TITLE
Mongoku + DocumentDB

### ISSUE THREAD

**Issue by tbjornli** [huggingface/Mongoku#79]
Have anyone been able to use Mongoku with DocumentDB?

I have tried to use the url provided to me by AWS which looks more or less like this:
```
mongodb://username:password@url.to.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&retryWrites=false
```
but I'm getting this error
```
failed to connect to server [server] on first connect [
  Error: unable to get local issuer certificate at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34) at TLSSocket.emit (events.js:400:28) at TLSSocket._finishInit (_tls_wrap.js:937:8) at TLSWrap.ssl.onhandshakedone (_tls.wrap.js:709:12) 
{ name: 'MongoNetworkError'}]
```

I have tried to download the **rds-combined-ca-bundle.pem** and place it in *node_modules/mongoku/dist/* and *node_modules/mongoku/dist/config/* folder without any luck.

Any ideas?

Also the documentation says that it is possible to define some configuration environment variables. Is it possible to set these in a specific file?

**Comment by saibimajdi** [comment]
I'm using DocumentDB and only this connection string format works for me.
`username:password@url.to.docdb.amazonaws.com:27017` without any additional parameters.
